spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sunbank}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
